
var shuffleSequence = seq("consent", "setcounter", "intro", "practice", "begin", sepWith("sep", randomize("similarity")), "sr", "debrief");
var practiceItemTypes = ["practice"];

var manualSendResults = true;

var defaults = [
    "Separator", {
        transfer: 500,
        hideProgressBar: true,
        normalMessage: "+"
    },
    "Message", {
        hideProgressBar: true
    },
    "AcceptabilityJudgment", {
        q: 'How similar are these two verbs?',
        as: ["1", "2", "3", "4", "5", "6", "7"],
        presentAsScale: true,
        instructions: "Use number keys or click boxes to answer.",
        leftComment: "Very dissimilar", rightComment: "Very similar"
    },
    "Form", { 
        hideProgressBar: true,
        continueOnReturn: false   
    }

];

var items = [
	["consent", "Form", {
        html: { include: "consent.html" },
		validators: {age: function (s) { if (s.match(/^\d+$/)) return true;
							else return "Bad value for age"; }}
    } ],

	["intro", "Message", {html: { include: "intro.html" }}],

	["practice", "AcceptabilityJudgment", {s: "crack | break"}],
	["practice", "AcceptabilityJudgment", {s: "eat | fail"}],
	["practice", "AcceptabilityJudgment", {s: "stand | sit"}],
	["practice", "AcceptabilityJudgment", {s: "tease | gouge"}],
	["practice", "AcceptabilityJudgment", {s: "park | drive"}],

	["begin", "Message", {
				html: { include: "begin.html" },
				} ],

        ["setcounter", "__SetCounter__", { }],
        ["sr", "__SendResults__", { }],

    ["sep", "Separator", { }],

    [["similarity",1], "AcceptabilityJudgment", {s: 'love | need'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'love | forget'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'forget | love'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'love | forbid'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'forbid | love'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'love | imagine'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'imagine | love'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'love | say'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'say | love'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'love | promise'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'promise | love'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'love | expect'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'expect | love'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'love | want'}],
[["similarity",1], "AcceptabilityJudgment", {s: 'want | love'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'need | love'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'love | hate'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'hate | love'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'love | worry'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'worry | love'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'love | guess'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'guess | love'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'love | amaze'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'amaze | love'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'love | feel'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'feel | love'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'love | doubt'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'doubt | love'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'love | tell'}],
[["similarity",2], "AcceptabilityJudgment", {s: 'tell | love'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'love | bother'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'love | hope'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'hope | love'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'love | hear'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'hear | love'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'love | demand'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'demand | love'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'love | believe'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'believe | love'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'love | realize'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'realize | love'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'love | deny'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'deny | love'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'love | remember'}],
[["similarity",3], "AcceptabilityJudgment", {s: 'remember | love'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'bother | love'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'love | pretend'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'pretend | love'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'love | see'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'see | love'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'love | suppose'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'suppose | love'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'love | allow'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'allow | love'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'love | understand'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'understand | love'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'love | think'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'think | love'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'love | know'}],
[["similarity",4], "AcceptabilityJudgment", {s: 'know | love'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'forget | hate'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'forget | forbid'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'forbid | forget'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'forget | imagine'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'imagine | forget'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'forget | say'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'say | forget'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'forget | promise'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'promise | forget'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'forget | expect'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'expect | forget'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'forget | want'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'want | forget'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'forget | need'}],
[["similarity",5], "AcceptabilityJudgment", {s: 'need | forget'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'hate | forget'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'forget | worry'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'worry | forget'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'forget | guess'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'guess | forget'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'forget | amaze'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'amaze | forget'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'forget | feel'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'feel | forget'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'forget | doubt'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'doubt | forget'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'forget | tell'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'tell | forget'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'forget | hope'}],
[["similarity",6], "AcceptabilityJudgment", {s: 'hope | forget'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'forget | pretend'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'forget | hear'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'hear | forget'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'forget | demand'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'demand | forget'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'forget | believe'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'believe | forget'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'forget | realize'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'realize | forget'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'forget | deny'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'deny | forget'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'forget | remember'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'remember | forget'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'forget | bother'}],
[["similarity",7], "AcceptabilityJudgment", {s: 'bother | forget'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'pretend | forget'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'forget | see'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'see | forget'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'forget | suppose'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'suppose | forget'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'forget | allow'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'allow | forget'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'forget | understand'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'understand | forget'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'forget | think'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'think | forget'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'forget | know'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'know | forget'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'forbid | imagine'}],
[["similarity",8], "AcceptabilityJudgment", {s: 'imagine | forbid'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'forbid | guess'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'forbid | say'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'say | forbid'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'forbid | promise'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'promise | forbid'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'forbid | expect'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'expect | forbid'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'forbid | want'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'want | forbid'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'forbid | need'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'need | forbid'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'forbid | hate'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'hate | forbid'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'forbid | worry'}],
[["similarity",9], "AcceptabilityJudgment", {s: 'worry | forbid'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'guess | forbid'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'forbid | amaze'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'amaze | forbid'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'forbid | feel'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'feel | forbid'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'forbid | doubt'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'doubt | forbid'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'forbid | tell'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'tell | forbid'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'forbid | hope'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'hope | forbid'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'forbid | hear'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'hear | forbid'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'forbid | demand'}],
[["similarity",10], "AcceptabilityJudgment", {s: 'demand | forbid'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'forbid | suppose'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'forbid | believe'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'believe | forbid'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'forbid | realize'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'realize | forbid'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'forbid | deny'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'deny | forbid'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'forbid | remember'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'remember | forbid'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'forbid | bother'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'bother | forbid'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'forbid | pretend'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'pretend | forbid'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'forbid | see'}],
[["similarity",11], "AcceptabilityJudgment", {s: 'see | forbid'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'suppose | forbid'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'forbid | allow'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'allow | forbid'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'forbid | understand'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'understand | forbid'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'forbid | think'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'think | forbid'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'forbid | know'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'know | forbid'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'imagine | say'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'say | imagine'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'imagine | promise'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'promise | imagine'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'imagine | expect'}],
[["similarity",12], "AcceptabilityJudgment", {s: 'expect | imagine'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'imagine | doubt'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'imagine | want'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'want | imagine'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'imagine | need'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'need | imagine'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'imagine | hate'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'hate | imagine'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'imagine | worry'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'worry | imagine'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'imagine | guess'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'guess | imagine'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'imagine | amaze'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'amaze | imagine'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'imagine | feel'}],
[["similarity",13], "AcceptabilityJudgment", {s: 'feel | imagine'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'doubt | imagine'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'imagine | tell'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'tell | imagine'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'imagine | hope'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'hope | imagine'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'imagine | hear'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'hear | imagine'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'imagine | demand'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'demand | imagine'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'imagine | believe'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'believe | imagine'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'imagine | realize'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'realize | imagine'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'imagine | deny'}],
[["similarity",14], "AcceptabilityJudgment", {s: 'deny | imagine'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'imagine | think'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'imagine | remember'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'remember | imagine'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'imagine | bother'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'bother | imagine'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'imagine | pretend'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'pretend | imagine'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'imagine | see'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'see | imagine'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'imagine | suppose'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'suppose | imagine'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'imagine | allow'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'allow | imagine'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'imagine | understand'}],
[["similarity",15], "AcceptabilityJudgment", {s: 'understand | imagine'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'think | imagine'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'imagine | know'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'know | imagine'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'say | promise'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'promise | say'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'say | expect'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'expect | say'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'say | want'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'want | say'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'say | need'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'need | say'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'say | hate'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'hate | say'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'say | worry'}],
[["similarity",16], "AcceptabilityJudgment", {s: 'worry | say'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'say | demand'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'say | guess'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'guess | say'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'say | amaze'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'amaze | say'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'say | feel'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'feel | say'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'say | doubt'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'doubt | say'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'say | tell'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'tell | say'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'say | hope'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'hope | say'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'say | hear'}],
[["similarity",17], "AcceptabilityJudgment", {s: 'hear | say'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'demand | say'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'say | believe'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'believe | say'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'say | realize'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'realize | say'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'say | deny'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'deny | say'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'say | remember'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'remember | say'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'say | bother'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'bother | say'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'say | pretend'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'pretend | say'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'say | see'}],
[["similarity",18], "AcceptabilityJudgment", {s: 'see | say'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'promise | need'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'say | suppose'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'suppose | say'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'say | allow'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'allow | say'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'say | understand'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'understand | say'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'say | think'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'think | say'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'say | know'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'know | say'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'promise | expect'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'expect | promise'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'promise | want'}],
[["similarity",19], "AcceptabilityJudgment", {s: 'want | promise'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'need | promise'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'promise | hate'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'hate | promise'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'promise | worry'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'worry | promise'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'promise | guess'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'guess | promise'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'promise | amaze'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'amaze | promise'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'promise | feel'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'feel | promise'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'promise | doubt'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'doubt | promise'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'promise | tell'}],
[["similarity",20], "AcceptabilityJudgment", {s: 'tell | promise'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'promise | bother'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'promise | hope'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'hope | promise'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'promise | hear'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'hear | promise'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'promise | demand'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'demand | promise'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'promise | believe'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'believe | promise'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'promise | realize'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'realize | promise'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'promise | deny'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'deny | promise'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'promise | remember'}],
[["similarity",21], "AcceptabilityJudgment", {s: 'remember | promise'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'bother | promise'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'promise | pretend'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'pretend | promise'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'promise | see'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'see | promise'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'promise | suppose'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'suppose | promise'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'promise | allow'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'allow | promise'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'promise | understand'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'understand | promise'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'promise | think'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'think | promise'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'promise | know'}],
[["similarity",22], "AcceptabilityJudgment", {s: 'know | promise'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'expect | doubt'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'expect | want'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'want | expect'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'expect | need'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'need | expect'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'expect | hate'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'hate | expect'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'expect | worry'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'worry | expect'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'expect | guess'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'guess | expect'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'expect | amaze'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'amaze | expect'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'expect | feel'}],
[["similarity",23], "AcceptabilityJudgment", {s: 'feel | expect'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'doubt | expect'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'expect | tell'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'tell | expect'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'expect | hope'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'hope | expect'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'expect | hear'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'hear | expect'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'expect | demand'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'demand | expect'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'expect | believe'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'believe | expect'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'expect | realize'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'realize | expect'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'expect | deny'}],
[["similarity",24], "AcceptabilityJudgment", {s: 'deny | expect'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'expect | think'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'expect | remember'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'remember | expect'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'expect | bother'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'bother | expect'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'expect | pretend'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'pretend | expect'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'expect | see'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'see | expect'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'expect | suppose'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'suppose | expect'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'expect | allow'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'allow | expect'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'expect | understand'}],
[["similarity",25], "AcceptabilityJudgment", {s: 'understand | expect'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'think | expect'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'expect | know'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'know | expect'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'want | need'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'need | want'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'want | hate'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'hate | want'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'want | worry'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'worry | want'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'want | guess'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'guess | want'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'want | amaze'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'amaze | want'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'want | feel'}],
[["similarity",26], "AcceptabilityJudgment", {s: 'feel | want'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'want | deny'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'want | doubt'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'doubt | want'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'want | tell'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'tell | want'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'want | hope'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'hope | want'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'want | hear'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'hear | want'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'want | demand'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'demand | want'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'want | believe'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'believe | want'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'want | realize'}],
[["similarity",27], "AcceptabilityJudgment", {s: 'realize | want'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'deny | want'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'want | remember'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'remember | want'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'want | bother'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'bother | want'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'want | pretend'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'pretend | want'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'want | see'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'see | want'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'want | suppose'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'suppose | want'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'want | allow'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'allow | want'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'want | understand'}],
[["similarity",28], "AcceptabilityJudgment", {s: 'understand | want'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'need | doubt'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'want | think'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'think | want'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'want | know'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'know | want'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'need | hate'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'hate | need'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'need | worry'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'worry | need'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'need | guess'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'guess | need'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'need | amaze'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'amaze | need'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'need | feel'}],
[["similarity",29], "AcceptabilityJudgment", {s: 'feel | need'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'doubt | need'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'need | tell'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'tell | need'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'need | hope'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'hope | need'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'need | hear'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'hear | need'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'need | demand'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'demand | need'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'need | believe'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'believe | need'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'need | realize'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'realize | need'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'need | deny'}],
[["similarity",30], "AcceptabilityJudgment", {s: 'deny | need'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'need | think'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'need | remember'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'remember | need'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'need | bother'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'bother | need'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'need | pretend'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'pretend | need'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'need | see'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'see | need'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'need | suppose'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'suppose | need'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'need | allow'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'allow | need'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'need | understand'}],
[["similarity",31], "AcceptabilityJudgment", {s: 'understand | need'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'think | need'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'need | know'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'know | need'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'hate | worry'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'worry | hate'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'hate | guess'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'guess | hate'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'hate | amaze'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'amaze | hate'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'hate | feel'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'feel | hate'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'hate | doubt'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'doubt | hate'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'hate | tell'}],
[["similarity",32], "AcceptabilityJudgment", {s: 'tell | hate'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'hate | bother'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'hate | hope'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'hope | hate'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'hate | hear'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'hear | hate'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'hate | demand'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'demand | hate'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'hate | believe'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'believe | hate'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'hate | realize'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'realize | hate'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'hate | deny'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'deny | hate'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'hate | remember'}],
[["similarity",33], "AcceptabilityJudgment", {s: 'remember | hate'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'bother | hate'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'hate | pretend'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'pretend | hate'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'hate | see'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'see | hate'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'hate | suppose'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'suppose | hate'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'hate | allow'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'allow | hate'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'hate | understand'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'understand | hate'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'hate | think'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'think | hate'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'hate | know'}],
[["similarity",34], "AcceptabilityJudgment", {s: 'know | hate'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'worry | demand'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'worry | guess'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'guess | worry'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'worry | amaze'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'amaze | worry'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'worry | feel'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'feel | worry'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'worry | doubt'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'doubt | worry'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'worry | tell'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'tell | worry'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'worry | hope'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'hope | worry'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'worry | hear'}],
[["similarity",35], "AcceptabilityJudgment", {s: 'hear | worry'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'demand | worry'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'worry | believe'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'believe | worry'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'worry | realize'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'realize | worry'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'worry | deny'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'deny | worry'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'worry | remember'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'remember | worry'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'worry | bother'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'bother | worry'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'worry | pretend'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'pretend | worry'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'worry | see'}],
[["similarity",36], "AcceptabilityJudgment", {s: 'see | worry'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'guess | doubt'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'worry | suppose'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'suppose | worry'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'worry | allow'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'allow | worry'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'worry | understand'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'understand | worry'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'worry | think'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'think | worry'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'worry | know'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'know | worry'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'guess | amaze'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'amaze | guess'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'guess | feel'}],
[["similarity",37], "AcceptabilityJudgment", {s: 'feel | guess'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'doubt | guess'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'guess | tell'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'tell | guess'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'guess | hope'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'hope | guess'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'guess | hear'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'hear | guess'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'guess | demand'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'demand | guess'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'guess | believe'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'believe | guess'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'guess | realize'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'realize | guess'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'guess | deny'}],
[["similarity",38], "AcceptabilityJudgment", {s: 'deny | guess'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'guess | think'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'guess | remember'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'remember | guess'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'guess | bother'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'bother | guess'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'guess | pretend'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'pretend | guess'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'guess | see'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'see | guess'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'guess | suppose'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'suppose | guess'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'guess | allow'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'allow | guess'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'guess | understand'}],
[["similarity",39], "AcceptabilityJudgment", {s: 'understand | guess'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'think | guess'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'guess | know'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'know | guess'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'amaze | feel'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'feel | amaze'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'amaze | doubt'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'doubt | amaze'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'amaze | tell'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'tell | amaze'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'amaze | hope'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'hope | amaze'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'amaze | hear'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'hear | amaze'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'amaze | demand'}],
[["similarity",40], "AcceptabilityJudgment", {s: 'demand | amaze'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'amaze | suppose'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'amaze | believe'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'believe | amaze'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'amaze | realize'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'realize | amaze'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'amaze | deny'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'deny | amaze'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'amaze | remember'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'remember | amaze'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'amaze | bother'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'bother | amaze'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'amaze | pretend'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'pretend | amaze'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'amaze | see'}],
[["similarity",41], "AcceptabilityJudgment", {s: 'see | amaze'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'suppose | amaze'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'amaze | allow'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'allow | amaze'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'amaze | understand'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'understand | amaze'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'amaze | think'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'think | amaze'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'amaze | know'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'know | amaze'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'feel | doubt'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'doubt | feel'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'feel | tell'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'tell | feel'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'feel | hope'}],
[["similarity",42], "AcceptabilityJudgment", {s: 'hope | feel'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'feel | pretend'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'feel | hear'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'hear | feel'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'feel | demand'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'demand | feel'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'feel | believe'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'believe | feel'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'feel | realize'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'realize | feel'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'feel | deny'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'deny | feel'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'feel | remember'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'remember | feel'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'feel | bother'}],
[["similarity",43], "AcceptabilityJudgment", {s: 'bother | feel'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'pretend | feel'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'feel | see'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'see | feel'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'feel | suppose'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'suppose | feel'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'feel | allow'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'allow | feel'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'feel | understand'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'understand | feel'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'feel | think'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'think | feel'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'feel | know'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'know | feel'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'doubt | tell'}],
[["similarity",44], "AcceptabilityJudgment", {s: 'tell | doubt'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'doubt | bother'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'doubt | hope'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'hope | doubt'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'doubt | hear'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'hear | doubt'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'doubt | demand'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'demand | doubt'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'doubt | believe'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'believe | doubt'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'doubt | realize'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'realize | doubt'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'doubt | deny'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'deny | doubt'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'doubt | remember'}],
[["similarity",45], "AcceptabilityJudgment", {s: 'remember | doubt'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'bother | doubt'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'doubt | pretend'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'pretend | doubt'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'doubt | see'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'see | doubt'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'doubt | suppose'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'suppose | doubt'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'doubt | allow'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'allow | doubt'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'doubt | understand'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'understand | doubt'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'doubt | think'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'think | doubt'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'doubt | know'}],
[["similarity",46], "AcceptabilityJudgment", {s: 'know | doubt'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'tell | bother'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'tell | hope'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'hope | tell'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'tell | hear'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'hear | tell'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'tell | demand'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'demand | tell'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'tell | believe'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'believe | tell'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'tell | realize'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'realize | tell'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'tell | deny'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'deny | tell'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'tell | remember'}],
[["similarity",47], "AcceptabilityJudgment", {s: 'remember | tell'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'bother | tell'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'tell | pretend'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'pretend | tell'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'tell | see'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'see | tell'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'tell | suppose'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'suppose | tell'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'tell | allow'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'allow | tell'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'tell | understand'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'understand | tell'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'tell | think'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'think | tell'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'tell | know'}],
[["similarity",48], "AcceptabilityJudgment", {s: 'know | tell'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'hope | pretend'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'hope | hear'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'hear | hope'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'hope | demand'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'demand | hope'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'hope | believe'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'believe | hope'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'hope | realize'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'realize | hope'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'hope | deny'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'deny | hope'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'hope | remember'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'remember | hope'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'hope | bother'}],
[["similarity",49], "AcceptabilityJudgment", {s: 'bother | hope'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'pretend | hope'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'hope | see'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'see | hope'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'hope | suppose'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'suppose | hope'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'hope | allow'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'allow | hope'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'hope | understand'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'understand | hope'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'hope | think'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'think | hope'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'hope | know'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'know | hope'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'hear | demand'}],
[["similarity",50], "AcceptabilityJudgment", {s: 'demand | hear'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'hear | suppose'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'hear | believe'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'believe | hear'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'hear | realize'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'realize | hear'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'hear | deny'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'deny | hear'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'hear | remember'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'remember | hear'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'hear | bother'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'bother | hear'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'hear | pretend'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'pretend | hear'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'hear | see'}],
[["similarity",51], "AcceptabilityJudgment", {s: 'see | hear'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'suppose | hear'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'hear | allow'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'allow | hear'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'hear | understand'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'understand | hear'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'hear | think'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'think | hear'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'hear | know'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'know | hear'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'demand | believe'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'believe | demand'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'demand | realize'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'realize | demand'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'demand | deny'}],
[["similarity",52], "AcceptabilityJudgment", {s: 'deny | demand'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'demand | think'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'demand | remember'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'remember | demand'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'demand | bother'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'bother | demand'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'demand | pretend'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'pretend | demand'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'demand | see'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'see | demand'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'demand | suppose'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'suppose | demand'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'demand | allow'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'allow | demand'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'demand | understand'}],
[["similarity",53], "AcceptabilityJudgment", {s: 'understand | demand'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'think | demand'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'demand | know'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'know | demand'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'believe | realize'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'realize | believe'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'believe | deny'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'deny | believe'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'believe | remember'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'remember | believe'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'believe | bother'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'bother | believe'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'believe | pretend'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'pretend | believe'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'believe | see'}],
[["similarity",54], "AcceptabilityJudgment", {s: 'see | believe'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'realize | bother'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'believe | suppose'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'suppose | believe'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'believe | allow'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'allow | believe'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'believe | understand'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'understand | believe'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'believe | think'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'think | believe'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'believe | know'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'know | believe'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'realize | deny'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'deny | realize'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'realize | remember'}],
[["similarity",55], "AcceptabilityJudgment", {s: 'remember | realize'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'bother | realize'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'realize | pretend'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'pretend | realize'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'realize | see'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'see | realize'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'realize | suppose'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'suppose | realize'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'realize | allow'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'allow | realize'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'realize | understand'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'understand | realize'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'realize | think'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'think | realize'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'realize | know'}],
[["similarity",56], "AcceptabilityJudgment", {s: 'know | realize'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'deny | think'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'deny | remember'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'remember | deny'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'deny | bother'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'bother | deny'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'deny | pretend'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'pretend | deny'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'deny | see'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'see | deny'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'deny | suppose'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'suppose | deny'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'deny | allow'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'allow | deny'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'deny | understand'}],
[["similarity",57], "AcceptabilityJudgment", {s: 'understand | deny'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'think | deny'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'deny | know'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'know | deny'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'remember | bother'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'bother | remember'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'remember | pretend'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'pretend | remember'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'remember | see'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'see | remember'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'remember | suppose'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'suppose | remember'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'remember | allow'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'allow | remember'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'remember | understand'}],
[["similarity",58], "AcceptabilityJudgment", {s: 'understand | remember'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'bother | think'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'remember | think'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'think | remember'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'remember | know'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'know | remember'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'bother | pretend'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'pretend | bother'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'bother | see'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'see | bother'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'bother | suppose'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'suppose | bother'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'bother | allow'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'allow | bother'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'bother | understand'}],
[["similarity",59], "AcceptabilityJudgment", {s: 'understand | bother'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'think | bother'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'bother | know'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'know | bother'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'pretend | see'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'see | pretend'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'pretend | suppose'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'suppose | pretend'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'pretend | allow'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'allow | pretend'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'pretend | understand'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'understand | pretend'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'pretend | think'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'think | pretend'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'pretend | know'}],
[["similarity",60], "AcceptabilityJudgment", {s: 'know | pretend'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'suppose | think'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'see | suppose'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'suppose | see'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'see | allow'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'allow | see'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'see | understand'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'understand | see'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'see | think'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'think | see'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'see | know'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'know | see'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'suppose | allow'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'allow | suppose'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'suppose | understand'}],
[["similarity",61], "AcceptabilityJudgment", {s: 'understand | suppose'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'think | suppose'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'suppose | know'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'know | suppose'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'allow | understand'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'understand | allow'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'allow | think'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'think | allow'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'allow | know'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'know | allow'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'understand | think'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'think | understand'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'understand | know'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'know | understand'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'think | know'}],
[["similarity",62], "AcceptabilityJudgment", {s: 'know | think'}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>6F1A0E9BD837452</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>8D2FB90E57C436A</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>8946FB3EA2D51C0</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>0386F2CADE51794</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>5B6D9E34C021FA8</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>1DBC076F23954A8</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>BC8205FDAE97643</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>4F6D12B935E780C</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>CA8E0DB69153247</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>E640195AC7BF283</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>BA92EDF70316548</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>319E548A0F2C6DB</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>E3409251B8D67FA</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>CDE5B364A07F289</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>B47EC96A1DF5820</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>EDC763402B1A5F9</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>1D563482BCF0A97</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>0EF47A16C35DB92</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>CD78139E45A60FB</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>AB2C6890E35417D</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>63D48E2B15C07A9</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>0129AFE8B5743D6</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>7184C3EA60FD295</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>7E6D802C5491BAF</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>5F28AD3B419EC67</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>F1DBC3627E405A8</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>F1C9A85BDE06374</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>709468325FCD1BE</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>CA6BD4F9E178305</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>89CDA76EF05B143</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>D3E7C2B0194A856</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>6E4091D2CAFB537</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>5DBA372984CE61F</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>97F8A6CB035E21D</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>02D914E8B6A7C53</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>745F389B120AC6D</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>4C8230D169E7AFB</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>F4628E350BA79C1</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>316D905CF4A728B</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>3EAB0D2C694758F</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>7C109DF3B46A258</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>97BFE3614CD0A52</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>C3D87946BA125F0</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>6930CB8174A2F5E</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>B4A8195CE072D3F</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>0F9DC84157B3E6A</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>8BA245ED9701CF3</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>0635CEA498D12FB</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>38E26B0917DCF54</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>C5D40F97B68E32A</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>5EB2A98F7D634C1</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>AB689F03EC4752D</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>B42610DECF59A87</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>2B41DE8C6A7F390</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>CA413E85FB67290</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>C47BFDA159630E2</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>692C4B8E157F0A3</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>8C53127FDBA409E</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>BC5427F81A9E6D0</b></center></p>"}],
[["debrief", 0], "Message", {html: "<p><center>Please enter the following code into Mechanical Turk.</center></p><p><center><b>F5D4E178CA320B9</b></center></p>"}]

];
